### ISSUE TITLE
Update 'Hacktoberfest Finder' with 2021 Branding 

### ISSUE THREAD

**Issue by duncanmcclean** [hacktoberfest-finder/hacktoberfest-finder#212]
[Hacktoberfest Finder](https://hacktoberfest-finder.netlify.app) needs to be updated to fit with the new 2021 branding.

_(don't do this until October or it won't count towards your PRs)_

**Comment by manojkrishnak** [comment]
Hi, can you provide more details on what should be done? like, do you mean to change the logo of the hacktoberfest ?

**Comment by duncanmcclean** [comment]
> Hi, can you provide more details on what should be done? like, do you mean to change the logo of the hacktoberfest ?

Yes - logo & colours

**Comment by manojkrishnak** [comment]
I will take this up. please assign it to me

**Comment by manojkrishnak** [comment]
could you please review and approve this pull request for hactoberfest

**Comment by duncanmcclean** [comment]
Reviewed & assigned!

**Comment by manojkrishnak** [comment]
can you please give "hacktoberfest-accepted" tag to all the contributions i have made? Is that tag given is the legit way to consider for hacktoberfest contribution?

**Comment by duncanmcclean** [comment]
Apologies, forgot to do it on this PR. It should already be on the other ones I've merged though.

**Comment by manojkrishnak** [comment]
> Apologies, forgot to do it on this PR. It should already be on the other ones I've merged though.

No Bro, actually on the other merge requests also it is not there. Could you please give that tag.

**Comment by duncanmcclean** [comment]
Fixed now 

![image](https://user-images.githubusercontent.com/19637309/135682860-202de601-07d0-486f-8a2b-ffa6abfe0ef5.png)

**Comment by manojkrishnak** [comment]
Is it only on the pull request that tag is required or on the issue also? If so, for other 2 issues this tag is not there. 
Sorry to ask you many questions, this is the first time i'm doing. Thank you :)

**Comment by duncanmcclean** [comment]
It'll just be the pull request it's needed on.

**Comment by manojkrishnak** [comment]
ok. Thank you Bro :)
