### ISSUE TITLE
Update list of sponsors in footer

### ISSUE THREAD

**Issue by duncanmcclean** [hacktoberfest-finder/hacktoberfest-finder#213]
The footer of the site needs to be updated with the up-to-date list of sponsors.

https://hacktoberfest-finder.netlify.app/

_(don't do this until October or it won't count towards your PRs)_

**Comment by Sugyanee** [comment]
Hello! Can I work on it?

**Comment by duncanmcclean** [comment]
> Hello! Can I work on it?

Sure! Although, any PRs opened before the 1st October won't be counted against your Hacktoberfest PR count.

**Comment by manojkrishnak** [comment]
Hi, can I take this?

**Comment by manojkrishnak** [comment]
can you please give "hacktoberfest-accepted" tag to all the contributions i have made?
