### ISSUE TITLE
Fix bug where title of issues go outside the card

### ISSUE THREAD

**Issue by duncanmcclean** [hacktoberfest-finder/hacktoberfest-finder#214]
![image](https://user-images.githubusercontent.com/19637309/135323230-0264fd7f-2d32-4796-8f49-0332beef1b02.png)

https://hacktoberfest-finder.netlify.app/

Most likely something CSS wise that need's changed... we're using Tailwind CSS on this project.

**Comment by menghif** [comment]
Hi, I would like to take this one.

**Comment by duncanmcclean** [comment]
> Hi, I would like to take this one.

Feel free. Bear in mind that PRs created before the 1st October won't count towards your number of Hacktoberfest PRs.

**Comment by manojkrishnak** [comment]
I have made required changes, please review and merge the pull request. 

![image](https://user-images.githubusercontent.com/28722629/135677173-c0372d40-0afb-489e-8651-96cfcd832466.png)

**Comment by manojkrishnak** [comment]
can you please give "hacktoberfest-accepted" tag to all the contributions i have made?
