### ISSUE TITLE
Update issue template to use the new Issue Forms format

### ISSUE THREAD

**Issue by duncanmcclean** [hacktoberfest-finder/hacktoberfest-finder#215]

**Comment by manojkrishnak** [comment]
can you provide some more on details on this? is this the card which is shown with issue details?

**Comment by duncanmcclean** [comment]
In fact, I'll leave this for now and do it myself at some point. Sorry for any confusion!

**Comment by manojkrishnak** [comment]
Hi @duncanmcclean  do you have anything else to be done on this repo? or Can i take this Issue template one? Feel free to tell if you have any task on your mind.

**Comment by duncanmcclean** [comment]
> Hi @duncanmcclean do you have anything else to be done on this repo? or Can i take this Issue template one? Feel free to tell if you have any task on your mind.

There's nothing open at the moment - sorry!
