### ISSUE TITLE
Embeds still shows 2019 due to outdated OG tags

### ISSUE THREAD

**Issue by faran4engg** [hacktoberfest-finder/hacktoberfest-finder#223]
## Description

<img width="561" alt="Screenshot 2021-10-02 at 10 08 52 PM" src="https://user-images.githubusercontent.com/24570234/135730539-3321cf61-a95c-4319-bca4-7fe97ca354b7.png">

## Steps to reproduce

1. Copy the link https://hacktoberfest-finder.netlify.app/
2. Share on any social media. 

## Environment
All

**Comment by faran4engg** [comment]
Hi There!
Could you please assign this issue to me?

**Comment by duncanmcclean** [comment]
Good shout - assigned!
