### ISSUE TITLE
Social images are out-of-date

### ISSUE THREAD

**Issue by duncanmcclean** [hacktoberfest-finder/hacktoberfest-finder#225]
## Description

The `twitter:image` and `og:image` images are out-of-date and need to be updated for this year's Hacktoberfest.

Current image: https://hacktoberfest-finder.netlify.app/img/issuefinder.png

**Comment by NaveenKharwar** [comment]
Hi @duncanmcclean, I'd love to contribute here. Would you mind providing the latest image?

**Comment by duncanmcclean** [comment]
I think we just used the one that's used on the main Hacktoberfest site.. so that would be this one: https://hacktoberfest.digitalocean.com/share-card.png

Alternatively, maybe we could come up with our own image with the same theme or whatever.

**Comment by faran4engg** [comment]
> I think we just used the one that's used on the main Hacktoberfest site.. so that would be this one: https://hacktoberfest.digitalocean.com/share-card.png
> 
> Alternatively, maybe we could come up with our own image with the same theme or whatever.

@duncanmcclean , Could you please share your thought on this image 😉

![Hacktober-Fest](https://user-images.githubusercontent.com/24570234/135731897-00cb3383-bd51-4e3e-bccd-90bd1e0f1fbd.png)
