### ISSUE TITLE
Language Filter is not working correctly

### ISSUE THREAD

**Issue by Knorrke** [hacktoberfest-finder/hacktoberfest-finder#227]
## Description

The language filter doesn't return projects using the selected language. You would expect it to work like the [github search](https://github.com/search?q=topic%3Ahacktoberfest+created%3A%3E%3D2020-01-01+language%3ABrainfuck&type=repositories)

## Steps to reproduce

1. Select a language with few github repositories (this will make it more obvious), e.g. Brainfuck
2. The projects loaded (usually) aren't using Brainfuck
![grafik](https://user-images.githubusercontent.com/11499926/135913489-4b07badf-8396-41af-b4b9-3f6df342284c.png)

## Environment

Browser: Firefox 92.0.1 (64-Bit), Chrome 94.0.4606.71 (64-Bit)

**Comment by Knorrke** [comment]
I checked with the graphql explorer, and it seems to be a problem with the query. It worked after I put spaces after the query lines https://github.com/hacktoberfest-finder/hacktoberfest-finder/blob/ca4f199eea8661cad6b7b02ddaa9f70320ccb163/src/js/app.js#L33-L35

**Comment by duncanmcclean** [comment]
Feel free to open a PR to fit it, if you can! 👍
